<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$config['type'] = [
						'banner' => [
									 'extra-large_maintain_ratio' 	=> 'true',
									 'extra-large_quality' 		  	=> '100%',
									 'extra-large_width' 		  	=> 640,
									 'small_maintain_ratio'   	  	=> 'true',
									 'small_quality' 		  	  	=> '100%',
									 'small_width' 		  	  	  	=> 320,
									 'medium_maintain_ratio'  		=> 'true',
									 'medium_quality' 		  		=> '100%',
									 'medium_width' 		  		=> 360,
									 'large_maintain_ratio'   		=> 'true',
									 'large_quality' 		  		=> '100%',
									 'large_width' 		  	  		=> 480,
								],
									
						'solution' => [
									 'extra-large_maintain_ratio' 	=> 'true',
									 'extra-large_quality' 		  	=> '100%',
									 'extra-large_width' 		  	=> 640,
									 'small_maintain_ratio'   	  	=> 'true',
									 'small_quality' 		  	  	=> '100%',
									 'small_width' 		  	  	  	=> 320,
									 'medium_maintain_ratio'  		=> 'true',
									 'medium_quality' 		  		=> '100%',
									 'medium_width' 		  		=> 360,
									 'large_maintain_ratio'   		=> 'true',
									 'large_quality' 		  		=> '100%',
									 'large_width' 		  	  		=> 480,
									 'icon_width' 		  	  	  	=> 48,
									 'icon_maintain_ratio'  		=> 'true',
									 'icon_quality' 		  		=> '100%',
									  ],	
						'gallery' => [
									 'extra-large_maintain_ratio' 	=> 'true',
									 'extra-large_quality' 		  	=> '100%',
									 'extra-large_width' 		  	=> 640,
									 'small_maintain_ratio'   	  	=> 'false',
									 'small_quality' 		  	  	=> '100%',
									 'small_width' 		  	  	  	=> 320,
									 'medium_maintain_ratio'  		=> 'true',
									 'medium_quality' 		  		=> '100%',
									 'medium_width' 		  		=> 360,
									 'large_maintain_ratio'   		=> 'true',
									 'large_quality' 		  		=> '100%',
									 'large_width' 		  	  		=> 480,
									 'icon_width' 		  	  	  	=> 48,
									 'icon_maintain_ratio'  		=> 'true',
									 'icon_quality' 		  		=> '100%',
									],
									
						'product' => [
									 'extra-large_maintain_ratio' 	=> 'true',
									 'extra-large_quality' 		  	=> '100%',
									 'extra-large_width' 		  	=> 640,
									 'small_maintain_ratio'   	  	=> 'true',
									 'small_quality' 		  	  	=> '100%',
									 'small_width' 		  	  	  	=> 320,
									 'medium_maintain_ratio'  		=> 'true',
									 'medium_quality' 		  		=> '100%',
									 'medium_width' 		  		=> 360,
									 'large_maintain_ratio'   		=> 'true',
									 'large_quality' 		  		=> '100%',
									 'large_width' 		  	  		=> 480,
									 'icon_width' 		  	  	  	=> 64,
									 'icon_maintain_ratio'  		=> 'true',
									 'icon_quality' 		  		=> '100%',
									],			

						'user' => [
									 'extra-large_maintain_ratio' 	=> 'true',
									 'extra-large_quality' 		  	=> '100%',
									 'extra-large_width' 		  	=> 400,
									 'small_maintain_ratio'   	  	=> 'true',
									 'small_quality' 		  	  	=> '100%',
									 'small_width' 		  	  	  	=> 120,
									 'medium_maintain_ratio'  		=> 'true',
									 'medium_quality' 		  		=> '100%',
									 'medium_width' 		  		=> 200,
									 'large_maintain_ratio'   		=> 'true',
									 'large_quality' 		  		=> '100%',
									 'large_width' 		  	  		=> 300,
									],

						'content' => [
									 'extra-large_maintain_ratio' 	=> 'true',
									 'extra-large_quality' 		  	=> '100%',
									 'extra-large_width' 		  	=> 640,
									 'small_maintain_ratio'   	  	=> 'true',
									 'small_quality' 		  	  	=> '100%',
									 'small_width' 		  	  	  	=> 320,
									 'medium_maintain_ratio'  		=> 'true',
									 'medium_quality' 		  		=> '100%',
									 'medium_width' 		  		=> 360,
									 'large_maintain_ratio'   		=> 'true',
									 'large_quality' 		  		=> '100%',
									 'large_width' 		  	  		=> 480,
									 ],
									 
						'category' => [
									 'extra-large_maintain_ratio' 	=> 'true',
									 'extra-large_quality' 		  	=> '100%',
									 'extra-large_width' 		  	=> 640,
									 'small_maintain_ratio'   	  	=> 'true',
									 'small_quality' 		  	  	=> '100%',
									 'small_width' 		  	  	  	=> 320,
									 'medium_maintain_ratio'  		=> 'true',
									 'medium_quality' 		  		=> '100%',
									 'medium_width' 		  		=> 360,
									 'large_maintain_ratio'   		=> 'true',
									 'large_quality' 		  		=> '100%',
									 'large_width' 		  	  		=> 480,
									 'icon_width' 		  	  	  	=> 48,
									 'icon_maintain_ratio'  		=> 'true',
									 'icon_quality' 		  		=> '100%',
									],			 

						'news' => [
									 'extra-large_maintain_ratio' 	=> 'true',
									 'extra-large_quality' 		  	=> '100%',
									 'extra-large_width' 		  	=> 640,
									 'small_maintain_ratio'   	  	=> 'true',
									 'small_quality' 		  	  	=> '100%',
									 'small_width' 		  	  	  	=> 320,
									 'medium_maintain_ratio'  		=> 'true',
									 'medium_quality' 		  		=> '100%',
									 'medium_width' 		  		=> 360,
									 'large_maintain_ratio'   		=> 'true',
									 'large_quality' 		  		=> '100%',
									 'large_width' 		  	  		=> 480,							 
									 ],	

						'testimonial' => [
									 'extra-large_maintain_ratio' 	=> 'true',
									 'extra-large_quality' 		  	=> '100%',
									 'extra-large_width' 		  	=> 640,
									 'small_maintain_ratio'   	  	=> 'true',
									 'small_quality' 		  	  	=> '100%',
									 'small_width' 		  	  	  	=> 320,
									 'medium_maintain_ratio'  		=> 'true',
									 'medium_quality' 		  		=> '100%',
									 'medium_width' 		  		=> 360,
									 'large_maintain_ratio'   		=> 'true',
									 'large_quality' 		  		=> '100%',
									 'large_width' 		  	  		=> 480,
									],									 				
												 
                    ];